### PR TITLE
Feature/572 individual characteristics modal

### PR DESCRIPTION
**Pull request by maxdiebold-erg**
## Related Issues:
* [HMW-572](https://jira.epa.gov/browse/HMW-572)

## Main Changes:
* Added a modal and trigger to the _Past Water Conditions_ list content, which shows the individual characteristics that make up each top-level characteristic group, along with their measurement counts.
  * The counts do not always align, i.e. a group's "Number of Measurements" may not equal the count calculated by adding each characteristic's "Number of Measurements". This is due to the fact that the WQP domain values service is missing a number of characteristics. This service was used to create the `characteristicsByGroup` mapping file (it is only provided in a ZIP CSV file, so parsing was done ahead of time; however, I have confirmed that the file's content is up-to-date).
* Moved the `characteristicsByGroup` file to the S3 bucket.
* Changed more occurrences of _CyAN_ to _Blue-Green Algae_ internally. A type mismatch was preventing content from rendering in the lists.
* Addressed a small map-related memory leak.
* Adjusted the `Modal` component to scroll when overflowing.

## Steps To Test:
1. Go to http://localhost:3000/community/dc/monitoring.
2. In the Past Water Conditions section, open an accordion item.
3. Click the information icon in the item's toggle table, next to a characteristic group.
4. Verify a modal appears with a list of individual characteristics and counts.
5. On the map, select the location shown below: 
overflow
6. Open the modal for the **Pesticides** group, and confirm the overflow is scrollable.
7. Repeat in the Overview tab.
8. Go to the Past Water Conditions section of http://localhost:3000/community/lake%20okeechobee/monitoring, then sort the list by **Monitoring Measurements**.
9. Open the **Nutrients** modal, and take note of the counts.
10. Adjust the date slider, then repeat step 8. The counts should differ.
11. Open the corresponding map popup (by clicking the location on the map, not by the _View on Map_ button, although the button can be used to find the location), and check the Nutrients characteristics counts again. They should match the counts found in the list.
12. Verify the CyAN content is loading correctly in the Current Water Conditions tab.

### CODE REVIEW

**Review by cschwinderg — CHANGES_REQUESTED** [review]
Looks good! I like that the papa parse stuff is out of the public folder now.

I noticed that for some locations the table is empty. I think for these instances we should display an info message. For an example: go to state/tribe page, select the `Hoopa Valley Tribe, California` tribe, go to the monitoring locations list, expand `CDR at Red Rock` location and click Other. 

Some of the miscounts are happening because the characterstic has `***retired***` in the name. We should probably ask EPA about what they want to do about these. They may just want a disclaimer that says something about out of date characteristics.

**Comment by maxdiebold-erg** [comment]
@cschwinderg Good point, there should be an info box when there is a count mismatch, I will reach out to the WQP team about those issues. While some are described as retired, others are missing from the domain values service without explanation. For example, the **S-191 SPILLWAY ON CANAL C-59 AT LAKE OKEECHOBEE** shows a miscount in the Nutrients group, and viewing the "Not Assigned" characteristics shows that 5 of the 6 account for the miscount, that otherwise look like others:

miscount

not-assigned

Modals with no characteristics should always be a mismatch, since groups with no measurements will not show in the table.

**Comment by maxdiebold-erg** [comment]
On second thought, I just remembered the `periodOfRecord` service returns the `CharacteristicType` (group) alongside each characteristic. I'd avoided that route since we were already using the mapping file, but it should be much more consistent.

**Review by cschwinderg — APPROVED** [review]
Looks good! All of the numbers match now!

**Pull request merged**
