### PR TITLE
feature/116_mapped-water-issues

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* https://jira.epa.gov/browse/HMW-116

## Main Changes:
* Fixed issues with the mappedWaterLayer showing up in the layer list but not showing up in the map.
  * The issue with this was because the sub layers have more restrictive scale limitations. The old code was only looking at the scale limitations of the parent layer.
* Added the "Demographic Indicators" layer to the zoom dependent layer list. I noticed that this one was available in the layer list all of the time, even though it has scale limitations.
* Removed the "Congressional" layer from the list of zoom dependent layers. I noticed this layer did not have any scale limitations.

## Steps To Test:
1. Navigate to http://localhost:3000/community
2. Zoom in one tick and check the layer list to see when the "Mapped Water (all)" layer is in the list
3. When the "Mapped Water (all)" layer is in the list, turn it on
4. Verify the layer is visible on the map
5. Zoom out one tick
6. Verify the layer is no longer visible on the map
7. Verify the layer is no longer available in the list
8. Repeat steps 2 - 7 with the "Demographic Indicators" layer
9. Repeat steps 2 - 7 with the "Watersheds" layer
10. Repeat steps 2 - 7 with the "State" layer

### CODE REVIEW

**Comment by cschwinderg** [comment]
@courtneymyers Sorry, I wasn't very clear on that. You are correct, you have to repeat those steps until the layer is available in the layer list. Most of these layers will have different zoom thresholds.

**Comment by courtneymyers** [comment]
> @courtneymyers Sorry, I wasn't very clear on that. You are correct, you have to repeat those steps until the layer is available in the layer list. Most of these layers will have different zoom thresholds.

No worries, that makes sense. Just wanted to check on a few more things:

1) It's working as you describe, and each of those layers disappear in the layer list and visually on the map when you zoom out to a certain threshold, but the "on/clicked" state remains, so once you zoom back in it reappears. I think this is a good thing – just noting what I'm observing

2) Is there a reason why "County" and "Congressional Districts" aren't zoom dependent, but "State" is, since they're smaller than states?

3) Similarly, should "Tribal Areas" be zoom dependent for consistency? Not saying they should be, just wondering if its been discussed.

**Comment by cschwinderg** [comment]
Whether a layer is zoom dependent or not is based on the thresholds provided by the layer. The counties and congressional districts layers do not provide a minScale value (no zoom thresholds) whereas the states layer does. The `zoomDependentLayers ` variable is really only needed to make the for loop a little more efficient, since it won't have to check layers that we know don't have zoom thresholds. 

Currently we just respect the zoom thresholds provided by the layers, so that we show as much data as we possibly can. We can add in our own min/max scales if we want to further restrict the zoom thresholds.

**Comment by courtneymyers** [comment]
> Currently we just respect the zoom thresholds provided by the layers, so that we show as much data as we possibly can. We can add in our own min/max scales if we want to further restrict the zoom thresholds.

Gotcha, thanks for the info. That makes sense – no need to add our own min/max now, but we could talk about that as a possible future enhancement (probably a fairly low value add though, so maybe not even necessary).

**Pull request merged**
