### PR TITLE
Feature/655 update dependencies

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* [HMW-655](https://jira.epa.gov/browse/HMW-655)
* [HMW-656](https://jira.epa.gov/browse/HMW-656)
* [HMW-657](https://jira.epa.gov/browse/HMW-657)
* [HMW-658](https://jira.epa.gov/browse/HMW-658)

## Main Changes:
* Updated 3rd party dependencies.
* Upgraded to React 18 with Max's help.
* Max switched from `styled-components` to `emotion` for styles. 
* Updated cypress tests.
  * I already ran the cypress tests and they are all passing.

## Steps To Test:
1. Try to test all features.
2. Run cypress tests
    * Note: If you run coverage, you may need to comment out lines 130 - 135 in the `cypress/support/commands.ts` file. The `cypress-image-snapshot` package doesn't seem to work in cypress 13 headless mode.

### CODE REVIEW

**Comment by maxdiebold-erg** [comment]
I noticed the fullscreen tribal map is botched, this probably occurred when updating the EPA template. The fullscreen functionality on the other pages is fine.

**Comment by cschwinderg** [comment]
The fullscreen map issue should be fixed now. It impacted both the state and the tribes. The issue was related to the EPA template upgrade. The dev site has the same issue. The state/tribe page was using a bootstrap `container` class that none of the other map pages were using, so something around that was changed. My changes just move away from that `container` class, to be more consistent with the other maps.

**Comment by maxdiebold-erg** [comment]
The fix looks good, yeah I couldn't find what changed surrounding that.

**Review by maxdiebold-erg — APPROVED** [review]
Everything looks good! 

I'll make a ticket about the unwanted tab behavior, but I don't think it needs to be addressed right now: it was already present, it's the case on all maps, and I'm not sure about an immediate solution.

**Comment by maxdiebold-erg** [comment]
I'm having trouble finding the sticky box issue.

For the focus trap, I'd say we could either do it manually or use the same package used for the modals.

**Comment by cschwinderg** [comment]
I'm going to go ahead and merge this in. I'll open a ticket for the sticky box issue once I find a reliable way to reproduce it.

**Pull request merged**
