### PR TITLE
Feature/swap reach router for react router

### PR DESCRIPTION
**Pull request by courtneymyers**
## Related Issues:
* N/A

## Main Changes:
Replaces use of `@reach/router` with `react-router` – important to do short-term, as our CI is failing because Reach Router has a peer dependency of an older version of react. Longer term, we'd want to do this anyway, as v6 of React Router is the [next iteration of the team behind both project's ideas](https://reactrouter.com/docs/en/v6/upgrading/reach):

> If we were to make a @reach/router v2, it would look pretty much exactly like React Router v6. So, the next version of @reach/router is React Router v6. In other words, there will be no @reach/router v2, because it would be the same as React Router v6.

## Steps To Test:
1. `cd client && npm ci`
2. Navigate everywhere in the app!

## TODO:
- [ ] Re-visit sharing `BrowserRouter` context with rendered markup used in popup, so we can navigate to a new location via react router's `navigate` instead of manually changing the window.location

### CODE REVIEW

**Comment by cschwinderg** [comment]
I'm still doing testing, but I found an issue. If you click on the map where there are no graphics and then click Yes on the "Change to this location" popup, the url will update but the page doesn't update. I'm seeing infinite loading spinners. This still works on the dev site though.

A similar issue happens on the state page map. The url updates to the community url, but the page never switches.

**Comment by courtneymyers** [comment]
> @courtneymyers I'm still doing testing, but I found an issue. If you click on the map where there are no graphics and then click Yes on the "Change to this location" popup, the url will update but the page doesn't update. I'm seeing infinite loading spinners. This still works on the dev site though.
> 
> A similar issue happens on the state page map. The url updates to the community url, but the page never switches.

Thanks for flagging that – looking into it...

**Comment by courtneymyers** [comment]
@cschwinderg thanks in advance for making the additional tickets we discussed:
- simplifying `WaterbodyInfo` by removing the `isPopup` prop and embracing composition by creating a new component just for popups that renders `WaterbodyInfo`
- revisiting how we can access the main app's location state (via react router's `BrowserRouter` context rendered at the top of the main app root) in the popups which are currently rendered to new react roots via ReactDOM

Thanks again for discussing, and if your tests pass, please feel free to merge this in!

**Review by cschwinderg — APPROVED** [review]
@courtneymyers This looks great! Thanks for making this switch.

I did notice another issue while running the cypress tests. When you search for gibberish (i.e., `kljkljklj`), we expect for the app to navigate back to the community home page (i.e., http://localhost:3000/community. Instead, the app is staying at http://localhost:3000/community/kljkljklj/overview and displaying infinite loading spinners. 

I think I'm going to go ahead and merge this in and then create a separate ticket for fixing this bug.

**Pull request merged**
