### PR TITLE
Feature/apply responsive updates

### PR DESCRIPTION
**Pull request by courtneymyers**
## Related Issues:
* https://jira.epa.gov/browse/HMW-122

## Main Changes:
* Responsive design updates for the Community pages. Initially, I focused on style updates to resolve issues Brad noticed in tables overflowing when viewing certain pages on his phone (Overview -> Monitoring & Sensors sub-tab), and worked my way across all community pages/tabs, refining all styles to be better optimized for small screens.
* Cleans up markup/styling in a few places – not all specific to narrow screen sizes
* Converts all pages touched to use styled components' `css` instead of `styled`

## Steps To Test:
1. Visit all the community pages, and shrink your browser window's width to under 560px. In particular, Brad mentioned the latest Samsung Galaxy fold phone, which can have a screen size of `300 x 521` pixels, so that'd be a good size to test across pages.

## TODO:
- [ ] Apply responsive design changes to other pages

### CODE REVIEW

**Review by cschwinderg — CHANGES_REQUESTED** [review]
These changes look great! Everything looks way better on mobile now.

I did find some other places that have similar issues or need some padding.

To reproduce most of these, open up Chrome dev tools, switch to mobile view, and select Galaxy Fold from the top toolbar. 

### Identified Issues
* [ ] - The "Impaired Assessed Waters" tab has row border lines overflowing the tab borders.
identifiedIssues-ImpairedWaters

* [ ] - The "Dischargers with Significant Violations" tab has some overflow, particularly when you click the accordion content. Search for the "020700100305" HUC to reproduce this one.
protect-WildScenicRivers

* [ ] - The "Dischargers with Significant Violations" tab also has no margin/padding around the content, which is really obvious when you select an item. Search for the "020700100305" HUC to reproduce this one.
identifiedIssuesDischargers-NoMargin

### Restore Tab
* [ ] - There is some overflow on the "Clean Water Act Section 319 Projects" tab. Go to http://localhost:3000/community/auburn%20al/restore to reproduce this one. 
restore-CleanWaterActTab

### No space below map
* [ ] - For the tabs that have the info message below the map (screenshot below is the swimming tab), I think there needs to be some space between the map and the info message. 
swimming-NoSpaceBelowMap

* [ ] - For the tabs that have counts below the map (screenshot below is the monitoring tab), I think needs some more space.
monitoring-NoSpaceBelowMap

* [x] - For the tabs that have subtabs under the map (screenshot below is the drinking water tab), I could go either way on. I just figured I would point this out.
drinkingWater-NoSpaceBelowMap

**Comment by cschwinderg** [comment]
Some of these are probably pre-existing issues. I just noticed them since I tested everything on desktop and mobile.

**Comment by courtneymyers** [comment]
> The "Dischargers with Significant Violations" tab also has no margin/padding around the content, which is really obvious when you select an item. Search for the "020700100305" HUC to reproduce this one.
> identifiedIssuesDischargers-NoMargin

Thank you for flagging this! The `AccordionItem` was missing the container with padding as its child, which is used on the other Community tabs. I'll add it in here.

**Comment by courtneymyers** [comment]
> ### No space below map
> For the tabs that have the info message below the map (screenshot below is the swimming tab), I think there needs to be some space between the map and the info message. swimming-NoSpaceBelowMap
> 
> For the tabs that have counts below the map (screenshot below is the monitoring tab), I think needs some more space. monitoring-NoSpaceBelowMap
> 
> For the tabs that have subtabs under the map (screenshot below is the drinking water tab), I could go either way on. I just figured I would point this out. drinkingWater-NoSpaceBelowMap

Thanks for pointing this out! They all should have space below the map. It's an easy fix, I just hadn't noticed it (admittedly, I was keeping the map hidden when working on these styles, so thanks for being thorough with your testing!).

**Comment by courtneymyers** [comment]
@cschwinderg the table styles should be working now... I'd never seen that before, but they weren't always being imported properly – I think it had something to do with the component hierarchy and where the exported style fragments were being imported from (although there shouldn't've been any circular dependencies or anything, so it was odd). In any case, I moved them to the top level "styles/index.js" file. I initially intended this file to be global "config" for styling (fonts, colors), but noticed at some point, someone put some react-select styling config in there... and I can see that being a good place to put shared style fragments that we may want to re-use across components. Eventually we could move exported style fragments out of the "components" folder and into this file (e.g. message box styles, key metrics styles, etc.).

**Review by cschwinderg — APPROVED** [review]
Looks great! Thank you for applying those fixes.

That issue sounds very strange. I've never seen anything like that either.

**Pull request merged**
