### PR TITLE
Feature/187 waterbody report table overflow

### PR DESCRIPTION
**Pull request by maxdiebold-erg**
## Related Issues:
* [HMW-187](https://jira.epa.gov/secure/RapidBoard.jspa?rapidView=864&view=detail&selectedIssue=HMW-187&quickFilter=2479)

## Main Changes:
* Added CSS rules to condense the "Plans to Restore Water Quality" table on the waterbody report page, which was previously overflowing its container.

## Steps To Test:
1. Visit a waterbody report page, e.g. [http://localhost:3000/waterbody-report/MDE_EASP/MD-02140205/2022](http://localhost:3000/waterbody-report/MDE_EASP/MD-02140205/2022)
2. Resize the screen to a mobile view
3. Scroll to the "Plans to Restore Water Quality" section
4. Check that the table does not overflow its border

### CODE REVIEW

**Comment by maxdiebold-erg** [comment]
@cschwinderg If the screen gets below 360px, the Date column will still overflow slightly, due to the rule:
```
const dateCellStyles = css`
  white-space: nowrap;
`;
```
which I assume was in place to keep the date legible.

**Review by cschwinderg — COMMENTED** [review]
Looks good!

I think for the date column maybe that style should be changed to the following:

```
const dateCellStyles = css`
  @media (min-width: 350px) {
    white-space: nowrap;
  }
`;
```

**Comment by courtneymyers** [comment]
> Looks good!
> 
> I think for the date column maybe that style should be changed to the following:
> 
> ```
> const dateCellStyles = css`
>   @media (min-width: 350px) {
>     white-space: nowrap;
>   }
> `;
> ```

@cschwinderg  we haven't talked about this, but I try and avoid arbitrary "magic number" media queries – for consistency across the app, I try and keep all media queries to increments of 10rem if possible, or 5rem if I need more granularity (e.g. that's usually 160px or 80px). So if you're making a change here, I'd make it `480px`:

```diff
const dateCellStyles = css`
-   white-space: nowrap;
+  @media (min-width: 480px) {
+      white-space: nowrap;
+  }
`;
```

There are bigger styling changes we should make for very narrow screen sizes than just the date text wrapping – the above fix is fine for now, for preventing the date text from causing overflow, but there's more styling refinements I'd like us to make to this page at some point (both for small screen sizes and larger ones).

**Comment by cschwinderg** [comment]
@courtneymyers Makes sense. I'll try to keep that in mind in the future.

**Comment by maxdiebold-erg** [comment]
@cschwinderg, @courtneymyers I decided to take advantage of that 5rem granularity and use 400px to get a little more out of the `nowrap` property. The date still does not overflow at that breakpoint.

**Review by cschwinderg — APPROVED** [review]

**Pull request merged**
