### PR TITLE
Feature/579 improving download legend

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* [HMW-579](https://jira.epa.gov/browse/HMW-579)

## Main Changes:
* Updated the legend widget to output a custom legend, since the OOB esri one doesn't show all legend items. One benefit of the custom legend is that it matches the HMW legend more closely.
  * This works by using the OOB esri widget to generate the map portion and then it tacks on the legend.
  * I started off using `jsPDF` and `jsPDF-autotable` to do this, but I found that I needed a 3rd library (`pdf-lib`) to merge two PDF files together. I just ended up using `pdf-lib` for all of the pdf generating logic.
  * I ended up removing the File Format and DPI settings.
* Added labels to unique value renderer. This was originally done because the OOB esri widget needed that to display in the legend. I decided to leave that in there since it adds a little more information to the code and may help us with esri stuff in the feature.
* Changed `All Waterbodies...` titles to `Surrounding Waterbodies...` for consistency.
* Updated the WSIO gradient icon to include the text in the SVG, instead of in a separate div. This makes it easier to output the gradient icon into the PDF.
* Fixed issue of loading spinner not showing up when uploading a file to the add data widget.

## Steps To Test:
1. Navigate to http://localhost:3000/community/020700100201/overview
2. Zoom in one level, so the `Mapped Water (all)` layer is available
3. Turn on all of the layers
4. Use the download widget to save a pdf
5. Verify everything is shown in the PDF
6. Use the Add Data Widget to upload a layer as a file
7. Verify a loading spinner is displayed
8. Expand the legend
9. Verify the `State Watershed Health Index` gradient looks good
10. Go to the Protect tab and expand `Watershed Health Scores`
11. Verify the gradient icon looks good here as well

## TODO:
- [x] Would like to look into making the legend display in multiple columns (2 or 3 depending on chosen layout). I might still try to include that in this PR, but if it doesn't make it that's fine.

### CODE REVIEW

**Review by maxdiebold-erg — CHANGES_REQUESTED** [review]
Nicely done, I'm glad the DOM is used to produce the legend. The multiple columns look great.

The margins around the legend pages look a bit slim, should those match the margins on the map page?

I've found a few consistent issues that I haven't yet been able to diagnose:
1. ~~In many cases, the _Land Cover_ legend in particular seems to jump out of the flow:~~ **EDIT:** This may have been due to a different test I'd forgotten to remove. However, after removing the test (which was setting a specific width and height on `img` elements), the _Land Cover_ legend no longer shows.
2. The "Searched Location" symbol, specifically, does not show up in the legend in outputs from Firefox.
3. Despite the `fontSize` settings, the A3 Landscape and A4 Landscape layouts have very different font sizes, resulting in a lot of empty space on the right side of the page in the A4 Landscape legend:
**A3**
a3

**A4**
a4

4. For portrait layouts in Firefox, I only see the last page of the legend.
last-page

**Comment by cschwinderg** [comment]
Good catches! 

I think I broke item 1 with my latest refactor.

I didn't test on Firefox. It looks like items 2, and 4 are related to Firefox. I don't see those issues in Chrome. I'll try to figure those out.

For item 3, Esri probably scales the font depending on the chosen layout so I will try to mimic that.

**Comment by maxdiebold-erg** [comment]
Also, I noticed that `pdf-lib` is a whopping 19.5 MB unpacked. Since this is a feature that may not often be used, and that will not be used on the initial load, it would be a good candidate for dynamic imports.

**Comment by cschwinderg** [comment]
For #3, can you double check that? I think that might be because FireFox automatically selects auto zoom when you open a PDF. When I switch the zoom to 100% they look pretty much the same to me. I think I am going to go ahead and bump the font size up to 12 though. 

A3
image


A4 
image

**Comment by cschwinderg** [comment]
I just fixed that new issue. I should be committing that fix soon.

**Comment by cschwinderg** [comment]
The issue of the first item in a new column not being indented should be fixed now. I updated the column width to be based on the layout to reduce the amount of whitespace.

**Comment by cschwinderg** [comment]
I went ahead and switched to dynamic imports. I think that should complete this pull request. 

I was unable to reproduce item #4 above. I've noticed that sometimes in local development the legend gets stuck if you make local changes and don't refresh the page. So maybe it was because of that or maybe I fixed it in one of my other commits.

Just curious. How did you get the 19.5 MB number for pdf-lib? 

In the Chrome dev tools its saying the package is about 1.7 MB.

Static Imports
  * Home: 28.2 MB (5.6 MB transferred)
  * Community: 43.7 MB (9.9 MB transferred)
  * Community/DC : 51.2 MB (12.6 MB transferred)
  * Download Button Click: 0

Dynamic Imports
  * Home: 26.5 MB (5.3 MB transferred)
  * Community : 42.1 MB (9.5 MB transferred)
  * Community/DC: 49.6 MB (12.2 MB transferred)
  * Download Button Click: 1.7 MB (1.4 MB transferred) - This one should just be dynamically importing pdf-lib, file-saver, PrintVM, and PrintTemplate packages.

**Review by maxdiebold-erg — APPROVED** [review]

**Comment by maxdiebold-erg** [comment]
Everything looks great!

**Pull request merged**
