### PR TITLE
Feature/426 integrate surrounding waterbodies monitoring

### PR DESCRIPTION
**Pull request by maxdiebold-erg**
## Related Issues:
* [HMW-426](https://jira.epa.gov/secure/RapidBoard.jspa?rapidView=864&view=detail&selectedIssue=HMW-426)

## Main Changes:
* Updated the `useAllFeaturesLayer` hook to employ separate layers for "local" and surrounding data, rather than selectively masking features.
* Refactored the `monitoringLocationsLayer` to use the `useAllFeaturesLayer` hook, combining it with the `surroundingMonitoringLocationsLayer`.
* Integrated the `monitoringLocationsLayer` and the `allWaterbodiesLayer` into the aggregate "Surrounding Features" widget.
    * I held off on refactoring/combining the waterbodies layers for now, and instead integrated the `allWaterbodiesLayer` as is. This is so the EPA team could start testing the functionality already in place, but it results in some less-than-ideal workarounds: the `waterbodyLayer` key is duplicated in the _Layers_ context, and renamed as needed, since the `SurroundingsWidget` compares the keys to those existing in `visibleLayers` to determine whether to show the layer in the widget. This also means that it was necessary to add `waterbodyLayer` to the `visibleLayers` object on the _Identified Issues_ tab (hidden from the list).
* Fixed an issue of dischargers not filtering correctly on the _Identified Issues_ tab.
* Removed the `BoundariesToggleLayer` class, it's sub-classes, and the `experimentalDecorators` allowance in `tsconfig.json`. 

## Steps To Test:
1. Compare the default visibility and functionality of the surrounding monitoring locations and waterbodies to the separate widgets in the production app, and verify they match.
2. Since the `monitoringLocationsLayer` was refactored pretty heavily, check that both its interior and surrounding features update as expected, especially on the _Monitoring_ tab, on the _Tribal_ pages, and on the _Monitoring Report_ pages.
3. Check that the "Surrounding Features" widget is not visible on the State _Advanced Search_ page map.
4. Navigate to http://localhost:3000/community/dc/identified-issues and check that dischargers are filtered correctly on the map and in the "Dischargers with Significant Violations" list. A single facility should be visible on the base layer, but the other HUC facilities and surrounding facilities should be visible when "Dischargers" is toggled on in the "Surrounding Features" widget.

### CODE REVIEW

**Review by cschwinderg — CHANGES_REQUESTED** [review]
Looks great! I like how much code is being removed (nearly 1000 lines shorter). 

I'm still reviewing the functionality and will update this as necessary. Here are some of the issues I found (some of which I communicated to you via Teams):
* The map on the waterbody report and plan summary pages are crashing because they don't have the `LayersProvider`. 
* The full screen widget on the monitoring report page does not work.
  * Will also need to check the waterbody report and plan summary pages after they are fixed.
* Nothing to change for this one yet. I noticed that the surrounding dischargers layer is not filtered down to dischargers with significant effluent violations on the identified issues tab. We can discuss this during today's meeting.
  * Loosly related, this feature of filtering on the identified issues tab could result in some confusing behavior with the portable map widget. If the user saves from the Identified Issues tab it will save the filtered dischargers.
* Popups for the surrounding monitoring locations don't work. On production we have a popup that just says `This cluster represents x stations`, which isn't particularly useful. Is it possible to have surrounding monitoring locations work the same as those in the huc (i.e., 1st click breaks the cluster and 2nd click opens the popup)?

**Comment by cschwinderg** [comment]
Here are some one more issue I found. 

* The checkboxes in the monitoring locations become checked shortly after I uncheck them (see gif below), which makes it difficult to get the filtered output that you want. In production they don't get reset until the download button is clicked. This behavior only happens in the list view on the right; the map popup works as expected.
monitoring-download-checkboxes

**Comment by maxdiebold-erg** [comment]
@cschwinderg  I _think_ the first issues are fixed, I'm still testing it a bit. I moved the layer initialization closer to where others are initialized, which is fine as long as the context provider stays at the page level.

I'm still looking into the accordion content for the monitoring locations. I'd found a similar issue during development, thought it was fixed but I guess not.

**Review by cschwinderg — APPROVED** [review]
Looks good!

I'll let you decide wether to merge this in as is and create a ticket for the 4th item or to wait and include the fix for the 4th item in this PR.

**Comment by maxdiebold-erg** [comment]
@cschwinderg I fixed the checkbox issue, not sure if you want to look at it before I merge this in. I'll keep looking into the surrounding clusters problem, I haven't been able to reproduce it yet. Also, I think I got into a state where the `allWaterbodiesLayer` visibility wasn't aligned with its visibility in the widget, but it's also hard to reproduce. I can look into the second problem while working on [HMW-432](https://jira.epa.gov/secure/RapidBoard.jspa?rapidView=864&view=detail&selectedIssue=HMW-432).

**Review by cschwinderg — APPROVED** [review]
Looks good! Thank you for fixing those issues.

I'm going to go ahead and merge this in.

**Pull request merged**
