### PR TITLE
Feature/726 more climate tab changes

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* [HMW-726](https://jira.epa.gov/browse/HMW-726)

## Main Changes:
* Removed fill from huc/county boundaries on extreme weather tab.
* Removed switch from drinking water systems.
* Fixed bug of weather events queries not using the layers definition expression (basically querying all weather events). This is what caused the weird issue where a location in Oklahoma had both an inland flood warning and a coastal flood warning.
  *  Note: There is a commit where I merged inland flooding and coastal flooding, but since I noticed and fixed this bug I reverted that change.
* Fixed issue of map not zooming to county on page refresh.

## Steps To Test:
1. Navigate to http://localhost:3000/community/180300030602/extreme-weather
2. Verify the Excessive heat switch turns on by default (it has a excessive heat watch)
3. Verify the map zooms to the county
4. Verify there is no fill on county or huc boundaries
5. Switch to a different tab
6. Verify the county/huc boundaries have fill again
7. Switch back to extreme weather
8. Verify the county/huc boundaries no longer have fill
9. Switch locations to verify other switches turn on when there are warnings, alerts, watches, etc.
10. Navigate to an inland location with a flood warning
11. Verify the coastal flooding row doesn't have the same warning as inland flooding row
12. Switch tabs ver

### CODE REVIEW

**Review by maxdiebold-erg — CHANGES_REQUESTED** [review]
Good catches on the other pages and other bug fixes!

I'm slightly confused about which switches should be on by default: in the example location provided, the extreme heat layer is turned on when entering the tab, but when navigating to [DC](http://localhost:3000/community/dc/extreme-weather), none of the _current sever weather events_ tabs are toggled on, although _Inland Flooding_ and _Extreme Heat_ both have features.

Also, it seems like the click area for the toggle switches is only on the circle, whereas the whole switch is clickable in other parts of the application.

I noticed that the controls seemed sluggish and turned on the React profiler's render indicator. It looks like there is some constant updating going on:

output

Also, something seems to have affected opening the Dams information popup. I can only open it briefly at first, then I can't open it at all. It looks like it is closing on each re-render, so this is probably related to the excessive rendering noted before.

**Comment by cschwinderg** [comment]
I'll look into the constant rendering issue. 

The switches that come on by default are those where there is a severe event (i.e., at least one fire, flood watch, flood warning, heat advisory, sever drought, extreme drought, etc.). Rain Expected, max temp, and min temp don't fall into that category. DC doesn't have any of these at the moment, so all switches are off.

**Comment by cschwinderg** [comment]
Good catch on the constant rendering issue! The updateVisibleLayers was being called constantly. Should be fixed now.

I also fixed the issue Brad noted about numbers in the right column wrapping.

**Comment by maxdiebold-erg** [comment]
Looks good! It's much smoother now. I think the issue I saw with the switches was related to the rendering, too, because that is no longer an issue.

**Review by maxdiebold-erg — APPROVED** [review]

**Pull request merged**
