### PR TITLE
Bugfix/446 fix saved data other pages

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* [HMW-446](https://jira.epa.gov/browse/HMW-446)

## Main Changes:
* Fixed issues with saving from the monitoring report, plan summary, state, tribe, and waterbody report pages.

## Steps To Test:
1. Navigate test saving from pages other than the community page
2. Verify that web maps in AGO match what you expect

### CODE REVIEW

**Comment by maxdiebold-erg** [comment]
@cschwinderg I'd forgotten to check the `ActionsMap` when updating the layers, so I pushed up a change fixing that. The `actionsLayer` wasn't being displayed previously, and it looks like we were using two different IDs for that layer across the app.

**Comment by cschwinderg** [comment]
@maxdiebold-erg That is weird. I haven't seen that issue on my end. I'll try the above code out, but I think that code should be fine. If it works well for me, I'll go ahead and include it with this PR.

**Comment by cschwinderg** [comment]
@maxdiebold-erg I went ahead and made the above change.

**Comment by maxdiebold-erg** [comment]
@cschwinderg Thanks! That is weird that you didn't see that issue.

**Pull request merged**
