### PR TITLE
Bugfix/107 legend issues

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* https://jira.epa.gov/browse/HMW-107
* https://jira.epa.gov/browse/HMW-117 (duplicate to be deleted)

## Main Changes:
* Fixed various issues with the legend
  1. Esri "No legend" text being displayed when there are custom HMW layers being shown in the legend.
  2. HMW "There are currently no items to display" text being displayed when there are layers being shown from the Add Data Widget.
  3. HMW layers being shown in the legend, even though the map zoom level is outside of the layer's zoom threshold. 
  4. Sometimes layers are duplicated in the legend. Basically, we were displaying our custom legend for the layer and esri was displaying the out of the box version.

Implementation Note: I couldn't find a good ESRI event to hook into to see if the Esri portion of the widget had anything to display. I ended up using MutationObserver to detect when Esri adds/removes the "No legend" text to/from the DOM and used this information to know whether the Esri portion of the legend was actually displaying anything. 

## Steps To Test:
* Issue 1 and 4
  1. Navigate to http://localhost:3000/community
  2. Open the Add Data Widget
  3. Add the "USA Flood Hazard Areas" layer
  4. Open the legend
  5. Verify the legend only says "There are currently no items to display"
      * NOTE: In production this currently says "There are currently no items to display" and "No legend" (simulates issue 1)
  6. Open the layer list 
  7. Turn on the "County" layer
  8. Verify the legend only displays "County" once
      * NOTE: In production this will display "County" twice (simulates issue 4)
  9. Zoom in until the "USA Flood Hazard Areas" layer is displayed
  10. Remove the "USA Flood Hazard Areas" layer
  11. Re-add the "USA Flood Hazard Areas" layer
  12. Zoom out until the "USA Flood Hazard Areas" layer is no longer visible
  13. Open the legend
  14. Verify the legend only says "County" once
      * NOTE: In production this will display "County" and "No legend" (simulates issue 1)

## Steps To Test:
* Issue 2
  1. Navigate to http://localhost:3000/community or refresh the page
  2. Open the Add Data Widget
  3. Add the "USA Flood Hazard Areas" layer
  4. Zoom in until the "USA Flood Hazard Areas" layer is displayed
  5. Open the legend
  6. Verify the legend only displays info for the "USA Flood Hazard Areas" layer
      * NOTE: In production this will display "There are currently no items to display" and "USA Flood Hazard Areas" layer info.
  
## Steps To Test:
* Issue 3
  1. Navigate to http://localhost:3000/community/dc/overview
  2. Turn off the "Waterbodies" layer and leave the "Surrounding Waterbodies" layer on
  3. Zoom out until the "Surrounding Waterbodies" layer is no longer visible
  4. Open the legend 
  5. Verify the legend only displays "Searched Location" and "HUC12 Boundaries"

### CODE REVIEW

**Comment by courtneymyers** [comment]
@cschwinderg starting to test this... I just went through the "Issue 1 and 4" steps to test and got to the last step (xiv) and am still seeing "County" (which is correct) and "No legend" below that (which is incorrect).

**Comment by courtneymyers** [comment]
Testing "Issue 2" – went through to the last step (vi) and I'm also seeing the "There are currently no items to display" above the "USA Flood Hazard Areas" legend.

**Comment by courtneymyers** [comment]
Sorry to be the bearer of bad news... tested "Issue 3" as well, and see the waterbodies in the legend above "Searched Location" and "HUC12 Boundaries"

**Comment by cschwinderg** [comment]
I'll take a look. What browser were you using? I'm wondering if this is a Safari issue.

**Comment by courtneymyers** [comment]
> I'll take a look. What browser were you using? I'm wondering if this is a Safari issue.

Thanks. Chrome (latest version, 98.0.4758.102)

**Comment by cschwinderg** [comment]
Hmm. I'm not sure. It's all working for me and I'm on the same version of Chrome. 

Are you sure you pulled down from the `bufix/107_legend-issues` branch?

**Comment by courtneymyers** [comment]
Weird, I'm almost certain I was on this branch earlier when I tested, but just switched back and re-tested and everything's working as you describe... Maybe it was a caching issue? I dunno... Either way, it's working now, so I'll assume it was a fluke before.

**Review by courtneymyers — APPROVED** [review]

**Comment by cschwinderg** [comment]
Weird. I'm glad it's working now though.

**Pull request merged**
