### PR TITLE
Feature/483 updated grid styles

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* [HMW-483](https://jira.epa.gov/browse/HMW-483)

## Main Changes:
* Changing the column sizes of grids in HMW so they are more equally sized.

## Steps To Test:
1. Navigate to http://localhost:3000/community/dc/overview
2. Verify the grids look good across all tabs 
    * Pay special attention to "Construction Stormwater" and "Industrial Stormwater" on discharger tabs

### CODE REVIEW

**Review by maxdiebold-erg — APPROVED** [review]
This looks a lot better. Some glossary terms still look a bit odd when viewed in a pop-up:

screenshot

It looks like getting rid of "flex" in the individual `rowCellStyles` might alleviate this issue:

screenshot

It does break some other styles, though. The flex styles in the cells are really just used to space adjacent elements in a single cell, e.g. the _(opens new browser tab)_ suffixes:

screenshot

so we could handle those individually. I'm fine with handling that at a later point, though.

**Comment by cschwinderg** [comment]
I went ahead and removed the flex from `rowCellStyles` and added some margin to the 2 instances where the `(opens new browser tab)` disclaimers show up in a `BoxContent` component.

Some point in the future we may want to consolidate the `disclaimerStyles`, but for now I'm good with just duplicating that.

**Comment by cschwinderg** [comment]
@maxdiebold-erg Do you mind taking a look at this again, just to make sure I'm not missing anything?

**Review by maxdiebold-erg — CHANGES_REQUESTED** [review]
I only see one more issue, which should be fixed by applying the disclaimer styles to the `small` elements:

screenshot

**Comment by cschwinderg** [comment]
Good catch! I fixed it in a slightly different way, which covers all 4 places.

**Review by maxdiebold-erg — APPROVED** [review]
Good and dry!

**Pull request merged**
