### PR TITLE
Feature/hotfix 2 5

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* [HMW-410](https://jira.epa.gov/browse/HMW-410)

## Main Changes:
* Fixed an issue of the attains page not loading.
* Added additional safe guards to prevent this issue from happening again in the future.

## Steps To Test:
1. Navigate to http://localhost:3000/attains
2. Verify the page loads
3. Search for `PFAS` in the `Impairment Category` column and verify that `PFAS` shows up
4. In the `attainsToHmwMapping.js` file, comment out the entry for `PFAS`.
5. Reload the `attains` page 
6. Verify the page loads
7. Search for `PFAS` in the `Impairment Category` column and verify that `PER- AND POLYFLUOROALKYL SUBSTANCES (PFAS)` shows up, instead of `PFAS`
8. In the `attainsToHmwMapping.js` file, uncomment the entry for `PFAS` and comment out the entry for `Trash`.
9. Navigate to http://localhost:3000/state/CA/water-quality-overview
10. Verify the page doesn't crash
11. Expand the `Top Reasons for Impairment...` accordion
12. Verify that `Trash` shows up bold, without any glossary links

### CODE REVIEW

**Comment by cschwinderg** [comment]
Don't merge this one in yet, as we might need to make some minor modifications.

**Review by maxdiebold-erg — APPROVED** [review]
Good fix! I know Wendy said new parameter groups are rarely added, but do you think this is something we should eventually move to S3?

**Comment by cschwinderg** [comment]
We probably should move this stuff to S3. I think the reason we haven't done it yet is because of the `GlossaryTerm` components being used in the sentence fields.

**Comment by maxdiebold-erg** [comment]
@cschwinderg That's a good point. In #790 I used `span` elements with data attributes to work around that problem, then rendered the glossary term after the data was loaded.

**Pull request merged**
