### PR TITLE
Feature/re organize cypress tests

### PR DESCRIPTION
**Pull request by courtneymyers**
## Related Issues:
* https://app.breeze.pm/projects/100762/cards/3331144

## Main Changes:
* Reorganizes  Cypress tests from directories to flat files for each route tested.
* Adds in missing "Aquatic Life" tests to the top level topic pages.
* Installs the latest version of Cypress (and supporting packages) to the top level "orchestrating" application, and adds necessary configuration.
* Moves e2e tests from "client" app to top level orchestrating app.
* Removes no longer needed Cypress (and supporting packages) and config from the "client" app.

## Steps To Test:
1. Remove no longer used packages from the **client** app:    
from `app/client` directory run: `npm ci`
2. Install new packages in **orchestrating app**:    
from `app` directory run: `npm ci`
3. Run Cypress e2e tests and ensure tests still work as before:    
from `app` directory run: `npm run cypress`

### CODE REVIEW

**Comment by courtneymyers** [comment]
@coobr01 we may want to talk about adjusting SonarQube's code duplication settings...there's going to be duplicated code blocks across tests – so I don't believe the same DRY heuristics shouldn't necessarily apply in e2e tests.

**Comment by coobr01** [comment]
No worries, i'm all for just adding the cypress.io test folder to the sonar qube config file at the root of the repo; do you want to do that as part of this PR?

**Comment by coobr01** [comment]
Additionally, this all looked good and worked for me 

image

**Comment by courtneymyers** [comment]
> @courtneymyers No worries, i'm all for just adding the cypress.io test folder to the sonarqube config file exclusion list at the root of the repo; do you want to do that as part of this PR?

That sounds great, @coobr01. Feel free to push that up to this branch (or I can do it – just let me know).

**Pull request merged**
