### PR TITLE
Enhancement/729 move configs to s3

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* [HMW-729](https://jira.epa.gov/browse/HMW-729)

## Main Changes:
* Moved most of the remaining config items to S3.

## Steps To Test:
* Community Page
  * Focus on waterbodies (overview and identified issues tab), monitoring locations (overview and monitoring tabs) and cyan (overview and monitoring tabs.
  * Test surrounding layers as well.
    * Test popups for surrounding USGS Streamgages. We will need to test the listviews once the issues with that service are resolved.
  * For monitoring locations test filtering.
*  Waterbody Report and Plan Summary pages
  * Test popups for waterbodies and surrounding monitoring locations.
* Monitoring Report
  * Test popups for monitoring locations and surrounding monitoring locations.
* State/Tribal Pages
  * Test popups for waterbodies, monitoring locations, and surrounding layers.
  * Navigate to http://localhost:3000/state/AL/water-quality-overview
  * Select "Lakes and Reservoirs" for the "Water Type"
  * Expand "Top Reaons for Impairment..."
  * Verify all rows are linked to the glossary (particularly "Acidity")

## TODO:
- [x] Will need to test USGS Stream Gauges, once that issue is resolved.

### CODE REVIEW

**Review by maxdiebold-erg — CHANGES_REQUESTED** [review]
Looks good! I only noticed one issue: if you open the popup for a waterbody on the Identified Issues tab **when surrounding waterbodies is turned off**, there will be no popup content.

image

This only seems to be the case on that tab.

**Comment by cschwinderg** [comment]
Good catch! Should be good now.

This uncovered another issue, (should be fixed). The info icons in waterbody popups resulted in an infinite loading spinner in the modal.

**Review by maxdiebold-erg — CHANGES_REQUESTED** [review]
Found one more, in the `TribalMapList` component, the definition of the popup template should be:
```javascript
    const popupTemplate = {
      outFields: ['*'],
      title: (feature) => getPopupTitle(feature.graphic.attributes),
      content: (feature) =>
        getPopupContent({
          feature: feature.graphic,
          navigate,
          lookupFiles: { attainsUseFields, services, stateNationalUses },
        }),
    };
```

EDIT: There are several other cases throughout the application (`ActionsMap`, `StateMap`, and `LocationMap`) where `services` or `stateNationalUses` are being passed directly to `getPopupContent`, though they are no longer parameters of that function. I believe they should be wrapped in `lookupFiles`, but I haven't tested it yet.

**Comment by cschwinderg** [comment]
I went ahead and updated the stream gages. This may need further updates depending on their response.

I noticed that they did a quiet update and now a 12-digit HUC is required for the `locationHUCTwelveDigitCode` filter, so I didn't include any code for stripping leading 0s from the HUC. I noticed the `active` and `agency` parameters no longer exist, so I removed those from our query. `active` wasn't actually used anywhere. For `agency`, I just started using `agencyCode` for the Organization Name field, so our sorting logic will still work and for consistency with past water conditions.

**Comment by maxdiebold-erg** [comment]
Looks good, and good catch on that bug!

**Review by maxdiebold-erg — APPROVED** [review]

**Pull request merged**
