### PR TITLE
Feature/hmw 65 upgrade cypress tests

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* https://jira.epa.gov/browse/HMW-65

## Main Changes:
* Updated cypress tests to work with new data and visual updates.
* Added some new tests (View on Map button and alert message).
* Added a readme to explain how to get the code coverage to work. Basically, this just makes it so cypress doesn't hold onto any of the test screenshots. This makes it so you can't go back and inspect the DOM when a test fails, but you can still see which tests fail. I just put this in a readme so that this flag is only used when producing the code coverage report.

## Steps To Test:
1. Run `npm run cypress`
2. Run the tests. 
    * Note: For me running the tests worked best using the Edge browser. Chrome was crashing a lot when running all tests. Running the tests individually works the best though.

### CODE REVIEW

**Comment by courtneymyers** [comment]
Thanks for working on this, @cschwinderg! I ran all the tests (individually) and had issues with two:
- `1-visual-test.spec.js`: multiple failures... I need to dig into this a bit more to see what caused them
- `community.spec.js`: two tests failed:
    - Protect Tab: Check that Protection Projects are displayed
    - HTTP Intercepts (single test)

I'll dig into those next week (half leaving this comment as reminder to myself which ones to look into).

**Comment by courtneymyers** [comment]
@cschwinderg I saw you pushed up a few commits, so I pulled down those and re-ran the two tests that were failing for me before. The community one passes now, but the visual test is still failing... I'll message you on MS Teams and maybe we can screenshare to investigate together...

**Comment by cschwinderg** [comment]
@courtneymyers Sounds good. I think the issue is likely caused by which browser we are using to run the tests. I've been using Edge when I run the tests because Chrome will hit out of memory errors, especially when running all tests.

I ran the visual tests locally using Chrome and they failed for me as well. It looks like something changed, either with Chrome or Cypress, such that snapshots now include components outside of the map (i.e., the location search component shows up now). 

For some reason the visual tests aren't repeatable in firefox, even if I recreate all of the snapshots. 

Maybe we can look into using electron if we can't use edge.

**Review by courtneymyers — APPROVED** [review]
Thanks, @cschwinderg! I'm still getting resolution mismatches (2x on my display...maybe because of my display's pixel resolution), but we discussed investigating that later.

**Pull request merged**
