### PR TITLE
Feature/190 station download styles

### PR DESCRIPTION
**Pull request by maxdiebold-erg**
## Related Issues:
* [HMW-190](https://jira.epa.gov/secure/RapidBoard.jspa?rapidView=864&view=detail&selectedIssue=HMW-190&quickFilter=2479)

## Main Changes:
* Condensed the monitoring location measurement download section. It matches the recent style changes in the `feature/76_download-data-entire-huc` branch.
* Added a *Total* row to the monitoring location characteristic groups table of checkboxes that tracks the total count of selected groups.
* Added initialization code for the selected checkboxes. Previously, clicking on a checkbox would do the opposite of the expected behavior.

## Steps To Test:
1. Go to the **Monitoring** tab of the **Community** page, e.g. [http://localhost:3000/community/dc/monitoring](http://localhost:3000/community/dc/monitoring)
2. Click the **Sample Locations** sub-tab
3. Scroll to the monitoring sample locations accordion, and expand one
4. Confirm that interaction with the checkboxes accurately updates the total count

### CODE REVIEW

**Comment by maxdiebold-erg** [comment]
@courtneymyers Yes I'll do that, I realize the styling strategy I used was a bit convoluted.

**Comment by maxdiebold-erg** [comment]
@courtneymyers Actually in re-reviewing what I had done, a lot of the markup and styles were done to ensure that the download icons wrapped as a group on small screens, then stayed below the label text if they did wrap. Otherwise, one icon might wrap, or the icons might be a part of wrapped label text.

While it may still be possible to simplify the styling, I think it would be good to keep the functionality.

**Comment by courtneymyers** [comment]
> @courtneymyers Actually in re-reviewing what I had done, a lot of the markup and styles were done to ensure that the download icons wrapped as a group on small screens, then stayed below the label text if they did wrap. Otherwise, one icon might wrap, or the icons might be a part of wrapped label text.
> 
> While it may still be possible to simplify the styling, I think it would be good to keep the functionality.

@maxdiebold-erg – makes sense. Can you apply similar changes to this branch that I made to your other PR: https://github.com/Eastern-Research-Group/mywaterway/pull/646/commits/d2e7e6037cd3f6ffaf49a184b445691bf9700755?

**Comment by maxdiebold-erg** [comment]
@courtneymyers Yes I can do that. I didn't realize custom classnames are to be avoided. What do you mean be, "we're using emotion"?

**Comment by courtneymyers** [comment]
> What do you mean be, "we're using emotion"?

Haha sorry, I forgot we're using [Styled Components](https://styled-components.com) in this project. [Emotion](https://emotion.sh) is another CSS-in-JS library with a similar API (they're essentially the same from a usage POV). I've both on several projects, and forgot this one uses Styled Components.

**Comment by courtneymyers** [comment]
Thanks, @maxdiebold-erg! Just going to remove the `infoLinkStyles` styles as those aren't needed, and will merge this in.

**Pull request merged**
