### PR TITLE
Feature/update community tabs

### PR DESCRIPTION
**Pull request by courtneymyers**
## Related Issues:
* https://app.breeze.pm/projects/100762/cards/3151043

## Main Changes:
* Updates community page tabs to be horizontally scrollable. This change was driven by the request to break up the "Fishing" tab into two tabs – "Eating Fish" and "Aquatic Life". We discussed the trade-offs with EPA on not showing all tabs at once – the biggest being engagement may decrease for tabs not initially shown on screen. Generally, keeping the number of tabs to a minimum would be the best solution here, but as that's not possible in this situation, we're going with an "overflow" approach where a few tabs are initially shown, and the user can scroll/swipe left or right to view more.

Depending on the user's screen width, they'll always see exactly 4.5 or 5.5 tabs – that's intentionally, as the text being cut off on the last tab is a visual cue for the user the content is scrollable.

I've also included dot indicators below the tabs which offer a number of affordances to the user:
1) gives a visual cue that there are a number of tabs, possible off screen
2) allows the user to click (or tab over to) a dot to immediately jump to a specific tab
3) dots are keyboard accessible, with hover/focus/active state indicating which tab is active or selected
4) dots (which really are anchor links) have a title attribute matching their corresponding tab's title text – that's a win for accessibility as screen readers should read that text, and users will see the "tooltip" text when hovering over each dot.

Since we're tracking analytics on which tabs are visited, we can re-assess post launch if users aren't visiting the latter tabs, and discuss possible alternate solutions.

## Steps To Test:
1. Visit the Community page, perform a search, and navigate to other tabs.

## TODO:
- [ ] Break apart the current "Fishing" tab content into two pages (move relevant content over into the "Aquatic Life" page. I held off on doing this here, as I wanted to be sure this was the approach we're taking first.

### CODE REVIEW

**Comment by courtneymyers** [comment]
Thanks, @cschwinderg. I'll address those two points individually, starting with the second:

> Second, the tab dots cause a full page load. So, if you navigate using the tab dots then all of the fetches run every time you change tabs.

Clicking a dot shouldn't reload your page – functionally it should be exactly the same as clicking a tab. We might need to screenshare so I can see that happening on your machine.

> First, if you are on the overview tab and you click on the last tab (the one that is cut in half) it will stay cut in half.

Yeah, I've been aware of this... I was thinking about trying to scroll the clicked tab to the center of the right panel. I could go back and work on this as a future enhancement after we merge this in.

> However, if you click on the tab dot that corresponds to that tab then the tabs will scroll so you can see the full tab.

That's related to your page reload comment – let's screenshare to see what's going on...

**Comment by courtneymyers** [comment]
@cschwinderg – thanks for flagging the page refresh issue. I'm still not sure why that functionality was happening only on Windows (or at least not on macOS)... I just pushed an update that should fix it. I tested on my Windows VM and it should be working as intended now.

**Comment by coobr01** [comment]
Seems ok on my Windows based machine using Chrome.

**Comment by courtneymyers** [comment]
Of course, @cschwinderg – thanks for catching that! And thanks @coobr01 for confirming too.

**Pull request merged**
