### PR TITLE
Feature/175 station headers

### PR DESCRIPTION
**Pull request by maxdiebold-erg**
## Related Issues:
* [HMW-175](https://jira.epa.gov/browse/HMW-175)

## Main Changes:
* Removed "Organization ID" and "Monitoring Site ID" from the accordion list headers.
* Added "Water Type" to the accordion list headers.
* Added "Organization ID" to the accordion list bodies.
* Updated the corresponding "Sort By" lists.

## Steps To Test:
1. Visit the `/community` page
2. Open the "Overview" or "Monitoring" tab
3. If in the "Overview" tab, open the "Monitoring & Sensors" sub-tab

## TODO:
- [x] PR #597 needs to be merged in before this one can be merged.

### CODE REVIEW

**Review by cschwinderg — CHANGES_REQUESTED** [review]
@maxdiebold-erg This looks great!

Can you also add the Organization ID to the `UsgsStreamgagesContent` component in the `WaterbodyInfo` component?

**Comment by maxdiebold-erg** [comment]
@cschwinderg Most definitely!

**Review by cschwinderg — APPROVED** [review]
Thanks for making that update!

**Comment by cschwinderg** [comment]
@maxdiebold-erg Just so your aware. 

I've been going through and merging develop into all of these branches. When I did that for this one the "Current Water Conditions" tab was added to the "Monitoring" panel. Because of this, I went ahead and propagated your header changes to this new tab.

**Pull request merged**
