### PR TITLE
Feature/98 refactor public index pages

### PR DESCRIPTION
**Pull request by cschwinderg**
## Related Issues:
* https://jira.epa.gov/browse/HMW-98
* https://jira.epa.gov/browse/HMW-134

## Main Changes:
* Cleaned up some of the code in the public index.html file.
* Switched from `document.location` to `window.location` across the app and cypress tests.
* Removed Internet Explorer specific code. 
  * While I was working on this ticket I went to test the app in IE and noticed that it did not load at all (syntax errors). I did some more research and found that Esri ended support for IE as of version 4.18. Esri says that apps using ArcGIS JS API will no longer work in IE. For more information see the following links: [ArcGIS System Requirements](https://developers.arcgis.com/javascript/latest/system-requirements/#:~:text=Supported%20browsers&text=Firefox%2093%20or%20later,Safari%2014%20or%20later) and [So Long Internet Explorer](https://www.esri.com/arcgis-blog/products/arcgis/announcements/so-long-internet-explorer-11/)
* Added an error message, only visible to IE users, that says the IE is not supported.

## Steps To Test:
1. Navigate to http://localhost:3000/community/dc/overview in a non IE browser
2. Verify the app still works
3. Verify there is not a message about IE not being supported
4. Open an IE browser 
5. Verify there is a message saying that IE is not supported

Note: I did steps 4 and 5 using IE 11, 10, 9, and 8 with browserstack and the message shows up correctly for all except for IE 8. None of the styles loaded in for IE 8, but [epa.gov](https://www.epa.gov/) has the same problem.

### CODE REVIEW

**Comment by courtneymyers** [comment]
@cschwinderg I love this. I just skimmed the code changes and on first glance it looks good. I'll need to test in IE with BrowserStack, and will confirm its working as expected. My only question right now is do we want to use that config file you created for browser version numbers? Is it not enough to trust that they're evergreen/auto updating browsers... I guess Safari isn't (and maybe should be handled specifically) but the others should be.

**Comment by cschwinderg** [comment]
@courtneymyers The main reason I made the config file is just in case something happens and we need to flag a browser as unsupported without doing a release. It probably isn't likely, but just in case. 

We do see older versions of Chrome in Google Analytics. I just checked hits for today and quite a few people are using older versions of Chrome. Some as old as version 80. Maybe these people have turned the auto update feature off. I'm not sure if it's possible, but maybe their IT systems force them to only update at certain intervals.

**Comment by courtneymyers** [comment]
haha the ESRI "System Requirements" page you link to shows a "Your browser is no longer supported..." message. I'm not suggesting you change that link at all, it's just funny that that page itself on ESRI's website has issues in IE.

**Review by courtneymyers — APPROVED** [review]
I'm working on another EPA app that uses a more modern/updated version of the "One EPA" template – we could create a separate ticket to do that (I'd be happy to do that at some point in the future).

**Comment by cschwinderg** [comment]
Haha yeah, Esri wasn't joking around when they said they were dropping support for IE. I don't think any of there stuff fully works in IE anymore.

Sounds good. I'll create a ticket for updating the One EPA template. I wish they would update the github repo they have for it.

**Pull request merged**
